name: Mailnesia Perl tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"

      - name: Install dependencies
        run: cpanm --installdeps . --skip-satisfied
        shell: bash

      - name: Create tables in postgres
        run: bash ./tools/psql-create-tables.sh
        env:
          postgres_host: localhost
          postgres_user: mailnesia
          PGPASSWORD: test
        shell: bash

      - name: Execute unit / function tests
        run: prove -lv t
        env:
          postgres_host: localhost
          postgres_user: mailnesia
          postgres_password: test
          redis_host: localhost

      - name: Execute e2e tests
        uses: MohamedRaslan/background_run_and_test@v1
        with:
          start: |
            morbo --listen http://*:3000 ./script/website-pages.pl
            morbo --listen http://*:3001 ./script/website.pl
            morbo --listen http://*:3002 ./script/api.pl
            morbo --listen http://*:3003 ./script/rss.pl
            perl ./script/clicker.pl

          wait-on: |
            http://localhost:3000
            http://localhost:3001/mailbox/test
            http://localhost:3002/api/mailbox/test
            http://localhost:3003/rss/test
          command: perl tools/test-mailnesia.pl
        env:
          postgres_host: localhost
          postgres_user: mailnesia
          postgres_password: test
          redis_host: localhost

    # Service containers to start
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379

      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: mailnesia
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
